name: Website
highlighter: pygments
<<<<<<< HEAD
baseurl: http://selectusa.github.io/mobile
=======
>>>>>>> origin/gh-pages
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
collections:
- events