name: Website
highlighter: pygments
baseurl: http://selectusa.github.io/mobile
plugins:
  - jekyll-redirect-from
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
collections:
- events